config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "New article created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])  
  end

  private

    def article_params
      params.require(:article).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<main class="col-sm-8">
  <%= flash[:success] %>

  <% @articles.each do |article| %>
    <h1 class="article-title"><%= link_to article.title, article_path(article) %></h1>
    <p class="article-meta"><%= article.created_at.strftime("%B %e, %Y") %></p>
    <article><%= article.content %></article>
  <% end %>

  <%= will_paginate %>
  
  <%= link_to "New article", new_article_path %>
</main>

app/views/articles/new.html.erb
<div class="col-sm-8">
  <h1 class="center">Create new article</h1>
  <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', rows: '25' %>

    <%= f.submit "Create", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/show.html.erb
<main class="col-sm-8">
  <%= flash[:success] %>
  <h1 class="article-title"><%= link_to @article.title, article_path(@article) %></h1>
  <p class="article-meta"><%= @article.created_at.strftime("%B %e, %Y") %></p>
  <article><%= @article.content %></article>
</main>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Blog built by <%= link_to "Alexey Kharkin", "https://github.com/Alexey-Kh" %>.</small>
  <p><%= link_to "Back to top", "#" %></p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to "blog", root_path, id: "logo" %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About me", "#" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log in", "#" %></li>
        <li><%= link_to "Sign up", "#" %></li>
      </ul> 
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar col-sm-3 col-sm-offset-1">
  <section id="sidebar-photo" class="sidebar-module">
    <%= image_tag "ror.png" %>
  </section>
  <section id="sidebar-description" class="sidebar-module">
    <%= render 'shared/sidebar_description' %>
  </section>
  <section id="sidebar-links" class="sidebar-module">
    <%= render 'shared/sidebar_links' %>
  </section>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <%= yield %>
      <%= render 'layouts/sidebar' %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_sidebar_description.html.erb
<p>This is Alexey Kharkin's blog covering Ruby on Rails and another information I can find useful and interesting.</p>

app/views/shared/_sidebar_links.html.erb
<h4>Additional Links</h4>
<nav>
  <ul class="list-unstyled">
    <li><%= link_to "My GitHub", "https://github.com/Alexey-Kh" %></li>
     <li><%= link_to "Rails documentation", "http://rubyonrails.org/documentation/" %></li>
  </ul>
</nav>